### PR TITLE
Update versions of gl and canvas for add support for Node v22

### PR DESCRIPTION
**Pull request by zdu-strong**

### CODE REVIEW

**Comment by drawcall** [comment]
Release npm later or you can remind me next week

**Comment by zdu-strong** [comment]
Can you release a new version?

**Comment by drawcall** [comment]
> Can you release a new version?

mark

**Comment by drawcall** [comment]
Oh, I am planning to release it, but is this PR backward compatible with Node.js versions 16, 18, and 20? @zdu-strong

**Comment by zdu-strong** [comment]
It supports Node.js v18, v20, v22.
Unfortunately, it does not support Node.js v16.

**Comment by drawcall** [comment]
> It supports Node.js v18, v20, v22. Unfortunately, it does not support Node.js v16.

Oh, I think it would be better to update a few months later. There are still many users using version 16. Thank you

**Pull request merged**
